### PR TITLE
 Update sortable demo to highlight issue with nested links and dragStart , fix issue

### PR DESCRIPTION
**Pull request by alibosworth**
In most cases, the dragStart/context methods were given the correct
elements: those that were targeted via options.itemSelector.  There was
an edge case where if the itemSelector element contains an A element
with an HREF attribute, it would be passed as the dragged element
rather than the parent that matched the selector.

Please test this by checking out `1fa3581` and seeing that the sortable.html demo shows the issue, then checking out `f1fab1a` to see that it fixes it

This is published to npm with a "testing" flag, so you can install via `npm install droppable.js@testing`

### CODE REVIEW

**Comment by alibosworth** [comment]
Anyone want to test this out?

**Comment by Rosey** [comment]
I tested it out briefly this morning and it seemed good, will test again further with task list dnd. I just tested it in chris's branch with fav sorting.

**Comment by Rosey** [comment]
yeah seems to be working well!

**Comment by Rosey** [comment]
want to clean up (remove testing release) so it can be merged?

**Comment by alibosworth** [comment]
Should i commit a bump to a full point version in the pr or not?

**Comment by Rosey** [comment]
I think it should be a minor release since it's a bug fix and is backwards-compatible?

**Comment by alibosworth** [comment]
sorry i meant minor, just didn't know if you wanted that to be done after this was merged to master

**Comment by Rosey** [comment]
Oh i see. My workflow is normally merge changes, do version bump and release separately. But I don't know if it's super important, just how I like to do it :P

**Comment by alibosworth** [comment]
ok will drop the force-pushed commit

**Comment by alibosworth** [comment]
done

**Pull request merged**
