### PR TITLE
Fix sortable index when options.manual is set to true

### PR DESCRIPTION
**Pull request by Rosey**
https://app.bananastand.org/workspaces/1/tasks/5639125

### CODE REVIEW

**Comment by Rosey** [comment]
Ci failures seem to be unrelated

**Comment by mogstad** [comment]
where

Still needs some tests though!

**Comment by Rosey** [comment]
Yes sir!

**Comment by Rosey** [comment]
done!

**Comment by Rosey** [comment]
bump!

**Pull request merged**
