### PR TITLE
Check cursor outside scrollable

### PR DESCRIPTION
**Pull request by 3mily**
- Rename cursorInsideElement to cursorOutsideElement to be more accurate
- Update cursorOutsideElement to check if element is scrolled out of view

### CODE REVIEW

**Comment by alibosworth** [comment]
hmm i wonder if we should make scrollableParent a configuration issue rather than hardcoding it based on our standard data attr

**Comment by Rosey** [comment]
Yeah I was hoping we could use `element.offsetParent` to achieve this and not need any additional config at all!

**Comment by 3mily** [comment]
hmm I'm afraid offsetParent wouldn't work because it isn't always going to be the scrollable container (eg. in out instance with the task list item droppable, the droppable element is an inner div within the task item element)

**Comment by 3mily** [comment]
>hmm i wonder if we should make scrollableParent a configuration issue rather than hardcoding it based on our standard data attr

Do you mean like setting an option of what the scrollableParent element is when setting up droppable?

**Comment by Rosey** [comment]
> hmm I'm afraid offsetParent wouldn't work because it isn't always going to be the scrollable container (eg. in out instance with the task list item droppable, the droppable element is an inner div within the task item element)

Okee you might be right but I wouldn't mind playing with this a bit next week just to see 😬 😁

**Comment by Rosey** [comment]
(me, not you!)

**Comment by 3mily** [comment]
i'm gonna close this because it's over a year old and we haven't had any reports of customers having trouble from the issues that this PR addresses.

**Pull request closed without merging**
