### PR TITLE
Tweak sortable to avoid issue with certain drops

### PR DESCRIPTION
**Pull request by alibosworth**
If sortable was initiated on element X which contained some non
sortable items (like a header or a footer), you could encounter certain
situations where the placeholder was shown correctly but nothing
registered upon drop. This was because all the events were attached in
a way which filtered on the @options.items selector, so the drop
event didn’t work if the drop event occurred when the mouse was over
the header or the footer. Instead all events are bound to the top
level element without a selector filter, and a few checks are added
where necessary.

https://next.bananastand.org/organizations/52/teams/1/tasks/5707762
https://app.bananastand.org/organizations/52/teams/1/tasks/5700051

Previous: https://github.com/flowapp/droppable.js/pull/16

### CODE REVIEW

**Comment by Rosey** [comment]
If you want to refactor `items` to `itemSelector` that seems like something that should be separate from the bug fix 🤔

**Comment by alibosworth** [comment]
Was thinking that!

**Comment by alibosworth** [comment]
rebasing onto master, there's also a problem with the elements that are passed to the context method that i'm debugging

**Comment by alibosworth** [comment]
updated and squashed and published as tag "beta" again

**Comment by Rosey** [comment]
Want to fix up so it can be merged?

**Comment by alibosworth** [comment]
yes i'll remove "-beta" from the version too

**Pull request closed without merging**
